import Head from 'next/head';
import { useState } from 'react';
// import { Inter } from '@next/font/google';

import { RealmDetails, Button } from '../components';

import styles from '../styles/Home.module.css';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [modalIsOpen, setIsOpen] = useState(false);

  function openModal() {
    setIsOpen(true);
  }

  // function afterOpenModal() {
  //   // references are now sync'd and can be accessed.
  // }

  function closeModal() {
    setIsOpen(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/1.1.0/modern-normalize.min.css"
          integrity="sha512-wpPYUAdjBVSE4KJnH1VR1HeZfpl1ub8YT/NKx4PuQ5NmX2tKuGu6U/JRp5y+Y8XG2tV+wKQpNHVUX03MfMFn9Q=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link
          rel="stylesheet"
          href="//db.onlinewebfonts.com/c/b2e75c336df191233b3096682c9ee6be?family=PixelarRegularW01-Regular"
          type="text/css"
        />
      </Head>
      <main className={styles.main}>
        <Button onClick={openModal}>Open Modal</Button>
        <RealmDetails isOpen={modalIsOpen} onClose={closeModal} />
      </main>
    </>
  );
}
